server:
  port: 9091
  servlet:
    context-path: /app2

spring:
  servlet:
    multipart:
      enabled: false
      max-request-size: 4GB
      max-file-size: 4GB

mns:
  demo:
    document:
      path: D:\project\mns\demo\document_download_upload\download
      upload:
        buffer-size: 8192
      download:
        buffer-size: 8192
      security:
        jwt-secret: 432ae535-3d97-486c-b6c6-3811054536f4
